### ISSUE TITLE
Service tracking issue for GSP-127: Add ServiceInternel and RequestThrottled Errors

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-service-minio#7]
- [Rendered GSP](https://github.com/beyondstorage/go-storage/blob/master/docs/rfcs/127-add-serviceinternel-and-requestthrottled-errors.md)
- [Tracking Issue](https://github.com/beyondstorage/go-storage/issues/612)

> This is the service tracking issue that generated by go-community, please close with comments if not applicable to this project.

## Steps

- [ ] Update `formatError` to add new errors check

**Comment by aeinrw** [comment]
This issues has been fixed！
https://github.com/beyondstorage/go-service-minio/blob/8735b8caf481def115833bc4a59b516e8fd2694b/utils.go#L150-L164
